services:
  mysql:
    image: mysql:8.0
    container_name: bankapp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 30s

    networks:
      - bankapp-net

  ollama:
    image: ollama/ollama
    container_name: bankapp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

    networks:
      - bankapp-net

  bankapp:
    image: arfat942/bank-app:distroless
    build: .
    container_name: bank-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankappdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      OLLAMA_URL: http://ollama:11434
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bankapp-net

volumes:
  mysql-data:
  ollama-data:

networks:
  bankapp-net:
    driver: bridge
