services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankapp-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -p$${MYSQL_ROOT_PASSWORD} --silent",
        ]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 30s

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - bankapp-net

  bankapp:
    build: .
    container_name: bank-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankappdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      OLLAMA_URL: http://ollama:11434
    ports:
      - "8080:8080"
    networks:
      - bankapp-net
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_started

volumes:
  mysql-data:
  ollama-data:

networks:
  bankapp-net:
    driver: bridge
