# docker run -d -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=root -p 3306:3306  

FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app
COPY . .

RUN chmod +x mvnw \
  && ./mvnw -DskipTests clean package \
  && cp target/*.jar /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]