# syntax=docker/dockerfile:1

FROM eclipse-temurin:21-jdk-jammy AS builder

WORKDIR /app

COPY . .

RUN chmod +x ./mvnw \
  && ./mvnw -DskipTests clean package \
  && JAR="$(ls -1 target/*.jar | grep -vE '(-plain|-sources|-javadoc)\.jar$' | head -n 1)" \
  && cp "$JAR" /app/app.jar


FROM gcr.io/distroless/java21-debian13:nonroot

WORKDIR /app

COPY  --from=builder  /app/app.jar /app/app.jar

EXPOSE 8080


ENTRYPOINT ["java", "-jar", "/app/app.jar"]