kind: Service
apiVersion: v1

metadata:
  name: bankapp-service
  namespace: bankapp
  labels:
    app: bankapp


spec:
  type: ClusterIP
  selector:
    app: bankapp

  ports:
    - port: 8080
      targetPort: 8080
 
