kind: PersistentVolume
apiVersion: v1

metadata:
  name: mysql-pv
  

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
      - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  hostPath:
    path: /home/ubuntu/AI-Bank/AI-Bank-App/mysqldata


