name: CICD
on:
  workflow_dispatch:
    inputs:
      evironment:
        description: this is the environment value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
            - dev
            - test
            - production
  push:
   paths:
     - "**.yml"
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo " github uploaded"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build the docker image
        run: echo "docker build"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "testing the app"
  deploy:
    if: inputs.evironment == "dev"
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy the app"
